services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: "npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - net

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - net

volumes:
  postgres_data:

networks:
  net: